### ISSUE TITLE
Namespace is always zkat even if it was changed in the node configuration

### ISSUE THREAD

**Issue by NorhanKhaled** [hyperledger-labs/fabric-token-sdk#256]
when adding a namespace in the configuration file of the node (not zkat),then when calling token.GetManagementService() and pass the node it will fail. it will throw error failed getting TMS for [{default mychannel zkat}]  although the namespace is not zkat

**Comment by adecaro** [comment]
Hi @NorhanKhaled, good catch.

Let me clarify what happens here: When invoking `token.GetManagementService()` without any additional option, the token-api tries to load the default TMS. What does this mean? The token-api checks if there is a default fabric or orion network configuration, if yes it consider that the default. For the channel, it is the same. For the namespace, the issue is that there can be multiple token namespaces in the same `<network, channel>`. So, the code currently uses the default namespace `zkat`.

So, the solution we can put forth is the following: The code can check the configuration and if there is a unique tuple <network, channel, namespace>, the code will use that one, otherwise it will fail.

Would this make sense?
